name = "twarchive"
license = "MIT"
licenselink = "https://github.com/mrled/twarchive/blob/master/LICENSE"
description = "Archive tweets permanently"
homepage = "https://github.com/mrled/twarchive"
tags = []
features = []
min_version = "0.96.0"

[author]
  name = "Micah R Ledbetter"
  homepage = "https://me.micahrl.com"
