baseURL: http://twarchive.example.org
languageCode: en-us
title: twarchive example site

# In production, use the published modules
# module:
#   imports:
#     - path: github.com/mrled/twarchive/aviary
#     - path: github.com/mrled/twarchive/ornithography

# In development, symlink these directories under themes/
theme:
- aviary
- ornithography

mediaTypes:
  text/html+tweet:
    suffixes: ["tweet.html"]

outputs:
  home:
    - HTML
  section:
    - HTML

outputFormats:
  HtmlTweet:
    mediatype: text/html+tweet
    suffix: tweet.html
    isPlainText: true
    notAlternative: false

params:
  dateform: "2006-01-02 03:04:05 -07:00"

disableKinds:
  - taxonomy
  - taxonomyTerm

menu:
  aviary:
    - name: Home
      url: /
      weight: 10
    - name: Tweets
      url: /twarchive
      weight: 20
    - name: Annotations
      url: /annotations
      weight: 30
