baseURL: http://twarchive.example.org
languageCode: en-us
title: twarchive example site

module:
  imports:
    - path: github.com/mrled/twarchive/aviary
    - path: github.com/mrled/twarchive/ornithography

mediaTypes:
  text/html+tweet:
    suffixes: ["tweet.html"]

outputs:
  home:
    - HTML
  section:
    - HTML
    - HtmlTweet

outputFormats:
  HtmlTweet:
    mediatype: text/html+tweet
    suffix: tweet.html
    isPlainText: true
    notAlternative: false

params:
  dateform: "2006-01-02 03:04:05 -07:00"

disableKinds:
  - taxonomy
  - taxonomyTerm
